trigger:
- main
- releases/

pool:
  vmImage: ubuntu-latest

variables:
- group: "SECURE_TOKENS"
- name: sonar_token
  value: $[variables.SONARTOKEN]

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo 'Building the code...'
      displayName: 'Building Azure DevOps App'

- stage: Test
  jobs:
  - job: TestJob
    steps:
    - script: echo 'Running tests...'
      displayName: 'Testing Azure DevOps App'

- stage: SAST
  jobs:
  - job: SASTScan
    steps:
    - script: |
        mvn verify package sonar:sonar -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.organization=azuredevopsdevsecopsorg10 -Dsonar.projectKey=azuredevopsdevsecopsorg10 -Dsonar.login=$(sonar_token)
      displayName: "SAST Scan Azure DevOps App with Code Coverage"
