trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: "SECURE_TOKENS"
- name: sonar_token
  value: $[variables.SONARTOKEN]

steps:
- script: |
    mvn verify package sonar:sonar -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.organization=azuredevopsdevsecopsorg -Dsonar.projectKey=azuredevopsdevsecopsprojectkey -Dsonar.login=$(sonar_token)
  displayName: "Integrate SAST using SonarCloud to populate code coverage in Azure DevOps DevSecOps Pipeline"
